rc_car:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  left_front_wheel_position_controller:
    type: effort_controllers/JointVelocityController
    joint: chassis_to_left_front_wheel
    pid: {p: 0.5, i: 0.0, d: 0.0, i_clamp: 0.0}
  left_rear_wheel_position_controller:
    type: effort_controllers/JointVelocityController
    joint: chassis_to_left_rear_wheel
    pid: {p: 1.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  right_front_position_controller:
    type: effort_controllers/JointVelocityController
    joint: chassis_to_right_front_wheel
    pid: {p: 0.5, i: 0.0, d: 0.0, i_clamp: 0.0}
  right_rear_position_controller:
    type: effort_controllers/JointVelocityController
    joint: chassis_to_right_rear_wheel
    pid: {p: 1.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  left_steering_hinge_position_controller:
    joint: left_steering_hinge_joint
    type: effort_controllers/JointPositionController
    pid: {p: 1.0, i: 0.0, d: 0.5}
  right_steering_hinge_position_controller:
    joint: right_steering_hinge_joint
    type: effort_controllers/JointPositionController
    pid: {p: 1.0, i: 0.0, d: 0.5}
